server:
  tomcat:
    uri-encoding: UTF-8
  port: 8867
  servlet:
    context-path: /cpu_synchronization_fk

spring:
  datasource:
    dynamic:
      primary: cpuPro #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        cpuPro:
          #内网
          url: jdbc:mysql://rr-2zedub9n0k3g0ct4y.mysql.rds.aliyuncs.com:3306/cpu?useunicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
          username: report_cpu_rd
          password: mZLuXSVd9j9kXcOe
          driver-class-name: com.mysql.jdbc.Driver
        loanJD:
          #内网
          url: jdbc:mysql://rm-2ze4g505tft2vp227.mysql.rds.aliyuncs.com:3306/loan?useunicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
          username: loan_uat_user
          password: Za@P@2522ZeE
          driver-class-name: com.mysql.jdbc.Driver
        riskModel:
          #内网
          url: jdbc:mysql://rm-2ze4g505tft2vp227.mysql.rds.aliyuncs.com:3306/ruleengine?useunicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
          username: loan_uat_user
          password: Za@P@2522ZeE
          driver-class-name: com.mysql.jdbc.Driver

  fromMysql:
    #内网
    hostname: rr-2zedub9n0k3g0ct4y.mysql.rds.aliyuncs.com
    port: 3306
    username: report_cpu_rd
    password: mZLuXSVd9j9kXcOe
mybatis:
    type-aliases-package: com.qinjia.pojo
    mapper-locations: classpath:mapper/*Mapper.xml

#该配置为删改表数据使用
delete:
  remark: 411381
